app/models.py
from . import db

class Envelope(db.Model):
    INCOME = 'income'
    EXPENCE = 'expence'

    __tablename__ = 'envelopes'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    type = db.Column(db.Enum(INCOME, EXPENCE), nullable=False, default=EXPENCE)

    def __repr__(self):
        return 'Envelope({0})'.format(self.id)

    def to_json(self):
        envelope_json = {
            'id': self.id,
            'type': self.type,
            'name': self.name
        }

        return envelope_json

class Budget(db.Model):
    __tablename__ = 'budgets'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    start_date = db.Column(db.Date, nullable=False)
    end_date = db.Column(db.Date, nullable=False)
    comment = db.Column(db.Text)

    envelopes = db.relationship('BudgetEnvelope', backref='budget')

    def __repr__(self):
        return 'Budget({0})'.format(self.id)

class BudgetEnvelope(db.Model):
    __tablename__ = 'budget_envelopes'

    id = db.Column(db.Integer, primary_key=True)
    amount = db.Column(db.Numeric(scale=2), default=0)
    about = db.Column(db.String)
    comment = db.Column(db.String)

    budget_id = db.Column(db.Integer, db.ForeignKey('budgets.id'))
    envelope_id = db.Column(db.Integer, db.ForeignKey('envelopes.id'))

    envelope = db.relationship('Envelope')

    def __repr__(self):
        return 'BudgetEnvelope({0})'.format(self.id)

app/main/forms.py
from app.models import Envelope
from flask_wtf import Form
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import Required

class EnvelopeForm(Form):
    name = StringField('Envelope name', validators=[Required()])
    type = SelectField('Envelope type', choices=[
        (Envelope.INCOME, Envelope.INCOME),
        (Envelope.EXPENCE, Envelope.EXPENCE),
    ])
    submit = SubmitField('Ok')

app/__init__.py
from config import config
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .admin import create_admin
    create_admin(app)

    from .api_1_0 import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api/v1.0')

    return app

app/admin/__init__.py
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

from .. import db
from ..models import Envelope, Budget



def create_admin(app):
    admin = Admin(app)

    admin.add_view(ModelView(Envelope, db.session))
    admin.add_view(ModelView(Budget, db.session))

    return admin

app/api_1_0/__init__.py
from flask import Blueprint, json
from ..models import Envelope

api = Blueprint('api', __name__)


@api.route('/envelopes/', methods=['GET'])
def get_envelopes():
    envelopes = [e.to_json() for e in Envelope.query.all()]

    return json.jsonify({
        'envelopes': envelopes
    })

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import errors
from . import views

app/main/views.py
from flask import render_template, redirect, url_for
from .. import db
from . import main
from ..models import Budget

@main.route('/', methods=['GET'])
def home():
    budgets = Budget.query.all()

    return render_template('home.html', budgets=budgets)

@main.route('/budget/new', methods=['GET'])
def budget_new():
    return render_template('budget_new.html')

@main.route('/budget/<int:id>/view')
def budget(id):
    budget = Budget.query.get_or_404(id)

    return render_template('budget.html', budget=budget)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Nestegg App{% endblock %}

{% block head %}
{{ super() }}
<link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='favicons/apple-touch-icon.png') }}">
<link rel="icon" type="image/png" href="{{ url_for('static', filename='favicons/favicon-32x32.png') }}" sizes="32x32">
<link rel="icon" type="image/png" href="{{ url_for('static', filename='favicons/favicon-16x16.png') }}" sizes="16x16">
<link rel="manifest" href="{{ url_for('static', filename='favicons/manifest.json') }}">
<link rel="mask-icon" href="{{ url_for('static', filename='favicons/safari-pinned-tab.svg') }}" color="#5bbad5">
<meta name="apple-mobile-web-app-title" content="Nestegg">
<meta name="application-name" content="Nestegg">
<meta name="theme-color" content="#ffffff">

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block content %}
    <nav class="navbar navbar-default  navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('main.home') }}">
                    <img src="{{ url_for('static', filename='egg-in-a-nest.png') }}" alt="Nestegg" height="20" width="20" />
                </a>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>

    <footer class="footer" style="    position: absolute;
    width: 100%;
    height: 60px;
    background-color: #f5f5f5;">
        <div class="container">
            <p class="text-muted">Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></p>
        </div>
    </footer>
{% endblock %}

app/templates/budget.html
{% extends "base.html" %}

{% block page_content %}

{% endblock %}

app/templates/budget_new.html
{% extends "base.html" %}

{% block page_content %}
    <div id="budget" class="col-lg-8 col-lg-offset-2"></div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/react.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/budget_create.js') }}"></script>
{% endblock %}

app/templates/envelopes/edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/envelopes/list.html
{% extends "base.html" %}
{% from "bootstrap/utils.html" import icon %}

{% block page_content %}
<a class="btn btn-block btn-primary">{{ icon('plus') }} add envelope</a>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% from "bootstrap/utils.html" import icon %}

{% block page_content %}
<h1>Budget list</h1>

<div class="row">
    <div class="col-md-2 col-sm-3">
        <a href="{{ url_for(main.budget_new) }}" class="btn btn-block btn-success">{{ icon('plus') }} add budget</a>
    </div>

    {% for b in budgets %}
    <div class="col-md-2 col-sm-3">
        <div class="budget-preview-pane center-block">
            <span>{{ b.name }}</span>
            <a href="{{ url_for('main.budget', id=b.id) }}" class="btn">{{ icon('th-list') }} view</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}